services:
  postgresql16:
    image: postgres:16.1
    ports:
      - "127.0.0.1:${POSTGRESQL16_PORT}:5432"
    volumes:
      - ./postgresql16_data:/var/lib/postgres
  postgresql13:
    image: postgres:13.13
    ports:
      - "127.0.0.1:${POSTGRESQL13_PORT}:5432"
    volumes:
      - ./postgresql13_data:/var/lib/postgres
  mysql5:
    image: mysql:5.7
    env_file: .env
    ports:
      - "127.0.0.1:${MYSQL5_PORT}:3306"
    volumes:
      - ./mysql5_data:/var/lib/mysql
  mysql8:
    image: mysql:8.0
    env_file: .env
    ports:
      - "127.0.0.1:${MYSQL8_PORT}:3306"
    volumes:
      - ./mysql8_data:/var/lib/mysql
  redis5:
    image: redis:5.0.5
    env_file: .env
    ports:
      - "127.0.0.1:${REDIS5_PORT}:6379"
    volumes:
      - ./redis5_data:/data
  redis6:
    image: redis:6.2.4
    env_file: .env
    ports:
      - "127.0.0.1:${REDIS6_PORT}:6379"
    volumes:
      - ./redis6_data:/data
  influxdb:
    image: influxdb:2.3.0
    ports:
      - "127.0.0.1:8088:8088"
      - "127.0.0.1:8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
  couchdb:
    image: couchdb:3.3.3
    env_file: .env
    ports:
      - "127.0.0.1:${COUCHDB_PORT}:5984"
    volumes:
      - ./couchdb_data:/var/lib/couchdb
